### ISSUE TITLE
how to draw transparent line

### ISSUE THREAD

**Issue by swaitw** [sebavan/BabylonjsInkSample#14]
Hi,
firstly , thanks for making this example which is very helpfull for me.
i am tring to make this example can draw line use RGBA color, but it did not work.

i tried to conver Color3 to Color4 when create ShaderMaterial ,but i faild.
so does anyone know how to do it?
waiting for you help.

thanks

**Comment by sebavan** [comment]
You would also need to change the creation of the ShaderMaterial to allow blending with its option needAlphaBlending set to true in the 4th parameter.

**Comment by swaitw** [comment]
> You would also need to change the creation of the ShaderMaterial to allow blending with its option needAlphaBlending set to true in the 4th parameter.

thanks for your reply, i tried, but still not work.
`  const shaderMaterial = new ShaderMaterial(
    name,
    scene,
    SimpleShaderConfiguration,
    {
      attributes: SimpleShaderConfiguration.attributes,
      uniforms: SimpleShaderConfiguration.uniformNames,
      needAlphaBlending: true,
    }
  );

  shaderMaterial.alpha = 0.5;

  // Sets the requested color on our shader
  // shaderMaterial.setColor3("color", color);
  shaderMaterial.setColor4("color", color.toColor4(0.5));`

**Comment by sebavan** [comment]
You d also need to modify the shaders for it to work to allow a float4 input and use your alpha.

Currently the shaders are forcing 1 for alpha: https://github.com/sebavan/BabylonjsInkSample/blob/master/src/materials/rainbowShader.ts#L67

**Comment by ASunKollide** [comment]
> You d also need to modify the shaders for it to work to allow a float4 input and use your alpha.
> 
> Currently the shaders are forcing 1 for alpha: https://github.com/sebavan/BabylonjsInkSample/blob/master/src/materials/rainbowShader.ts#L67

thanks a lot ,it works now. i got another question, how can i use visibility for Pahmesh, currently there is no effect when i change visibility  of Pathmesh.
thanks again for your help.

**Comment by sebavan** [comment]
You would need to pass it in the shader as a uniform and multiply it with the vertex alpha for the color output
